### Derivative Pricing using the Binomial Model

The below code implements the application Binomial Model in Derivative securities like Futures, European Call and Put Options with fixed interest rates over all the periods

In [7]:
import numpy as np
import math

#### Inputs For the Binomial Lattices

In [8]:
"""
N = number of binomial iterations
S0 = initial stock price
u = factor change of upstate
r = annual risk free rate
K = strike price
"""

N = input("Enter the Number of Binomial Periods:")
N = int(N)

S0 = input("Enter Initial Stock Price:")
S0 = float(S0)

u = input("Factor Change in Upmove:")
u = float(u)

r = input("Risk Free Rate:")
r = float(r)

K = input("Strike Price:")
K = float(K)

Enter the Number of Binomial Periods:3
Enter Initial Stock Price:100
Factor Change in Upmove:1.1
Risk Free Rate:0.1
Strike Price:105


#### Generating Stock Lattice for Binomial Model

In [9]:
stock = np.zeros([N+1,N+1])
d = 1 / u
for i in range(N+1):
    for j in range(i+1):
        stock[j,i] = S0*(u**(i-j))*(d**j)
        
print(stock)

[[100.         110.         121.         133.1       ]
 [  0.          90.90909091 100.         110.        ]
 [  0.           0.          82.6446281   90.90909091]
 [  0.           0.           0.          75.13148009]]


#### Future Lattice

In [18]:
def future_binomial_model(N, S0, u, r):
    
    d = 1 / u
    p = (1 + r - d) / (u - d)
    q = 1 - p
    
    future = np.zeros([N+1,N+1])
    future[:, N] = stock[:, N]
    for i in range(N-1,-1,-1):
        for j in range(0, i + 1):
            future[j,i] = (p * future[j, i + 1] + q * future[j + 1, i + 1])
    
    return future

#### Europian Option Lattice

In [16]:
def option_binomial_model(N, S0, u, r, K, Call = True):

    d = 1 / u
    p = (1 + r - d) / (u - d)
    q = 1 - p

    # make stock price tree
    stock = np.zeros([N + 1, N + 1])
    for i in range(N + 1):
        for j in range(i + 1):
            stock[j, i] = S0 * (u ** (i - j)) * (d ** j)

    # Generate option prices recursively
    option = np.zeros([N + 1, N + 1])
    
    if Call:
        option[:, N] = np.maximum(np.zeros(N + 1), (stock[:, N] - K))
    else:
        option[:, N] = np.maximum(np.zeros(N + 1), (K - stock[:, N]))
        
    for i in range(N - 1, -1, -1):
        for j in range(0, i + 1):
            option[j, i] = (
                1 / (1 + r) * (p * option[j, i + 1] + q * option[j + 1, i + 1])
            )
    return option

array([[21.11194591, 23.2231405 , 25.54545455, 28.1       ],
       [ 0.        ,  4.1322314 ,  4.54545455,  5.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ]])

In [17]:
print("Calculating example option price:")
op_price = option_binomial_model(N, S0, u, r, K)
print(op_price)
    
    
print("Generating Future Lattice:")
ft_price = future_binomial_model(N, S0, u, r)
print(ft_price)

Calculating example option price:
[[21.11194591 23.2231405  25.54545455 28.1       ]
 [ 0.          4.1322314   4.54545455  5.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]]
Generating Future Lattice:
[[133.1        133.1        133.1        133.1       ]
 [  0.         110.         110.         110.        ]
 [  0.           0.          90.90909091  90.90909091]
 [  0.           0.           0.          75.13148009]]
